### ISSUE TITLE
Sample not run.

### ISSUE THREAD

**Issue by mimrank** [roanuz/cricketapi-nodejs#1]
we try to run this sample but it through gulp start error.
`assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (\cricketapi-nodejs\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (\cricketapi-nodejs\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (\cricketapi-nodejs\gulpfile.js:31:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-cricket-app@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-cricket-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by rz-arun** [comment]
Hi @mimrank ,
Thanks for using Roanuz CricketAPI. I guess you are using Gulp v4 that’s why you got this error. We noticed its not supported by the code for now. We will add Gulp v4 support very soon.

**Comment by mimrank** [comment]
> Hi @mimrank ,
> Thanks for using Roanuz CricketAPI. I guess you are using Gulp v4 that’s why you got this error. We noticed its not supported by the code for now. We will add Gulp v4 support very soon.

any solution of it? and also any time frame for using Gulp v4?

**Comment by rz-arun** [comment]
You can use Gulp v3 for time being.
